# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spectrum.providers.imessage._proto.photon.imessage.v1 import address_service_pb2 as photon_dot_imessage_dot_v1_dot_address__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in photon/imessage/v1/address_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AddressServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    All RPCs share the same `address` query rules:

    - accept an E.164 phone number such as `+14155550123`
    - accept a full email such as `alice@example.com`
    - the server trims whitespace and lowercases email queries before lookup
    or external availability checks
    - empty or malformed inputs are rejected with `INVALID_ARGUMENT`
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAddressInfo = channel.unary_unary(
                '/photon.imessage.v1.AddressService/GetAddressInfo',
                request_serializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetAddressInfoRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetAddressInfoResponse.FromString,
                _registered_method=True)
        self.GetFocusStatus = channel.unary_unary(
                '/photon.imessage.v1.AddressService/GetFocusStatus',
                request_serializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetFocusStatusRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetFocusStatusResponse.FromString,
                _registered_method=True)
        self.GetIMessageAvailability = channel.unary_unary(
                '/photon.imessage.v1.AddressService/GetIMessageAvailability',
                request_serializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetIMessageAvailabilityRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetIMessageAvailabilityResponse.FromString,
                _registered_method=True)


class AddressServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    All RPCs share the same `address` query rules:

    - accept an E.164 phone number such as `+14155550123`
    - accept a full email such as `alice@example.com`
    - the server trims whitespace and lowercases email queries before lookup
    or external availability checks
    - empty or malformed inputs are rejected with `INVALID_ARGUMENT`
    """

    def GetAddressInfo(self, request, context):
        """Returns services seen and country for the address.

        Errors: NOT_FOUND when the address has never been seen in this device's
        iMessage history.

        Over HTTP, `address` is a query parameter (addresses contain `+`, which
        is path-hostile) — remember to URL-encode it (`%2B`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFocusStatus(self, request, context):
        """Returns whether Messages currently reports this address as Focus-silenced.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIMessageAvailability(self, request, context):
        """Returns whether the address is reachable via iMessage at query time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAddressInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddressInfo,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetAddressInfoRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetAddressInfoResponse.SerializeToString,
            ),
            'GetFocusStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFocusStatus,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetFocusStatusRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetFocusStatusResponse.SerializeToString,
            ),
            'GetIMessageAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIMessageAvailability,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetIMessageAvailabilityRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_address__service__pb2.GetIMessageAvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photon.imessage.v1.AddressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photon.imessage.v1.AddressService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AddressService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    All RPCs share the same `address` query rules:

    - accept an E.164 phone number such as `+14155550123`
    - accept a full email such as `alice@example.com`
    - the server trims whitespace and lowercases email queries before lookup
    or external availability checks
    - empty or malformed inputs are rejected with `INVALID_ARGUMENT`
    """

    @staticmethod
    def GetAddressInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.AddressService/GetAddressInfo',
            photon_dot_imessage_dot_v1_dot_address__service__pb2.GetAddressInfoRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_address__service__pb2.GetAddressInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFocusStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.AddressService/GetFocusStatus',
            photon_dot_imessage_dot_v1_dot_address__service__pb2.GetFocusStatusRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_address__service__pb2.GetFocusStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIMessageAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.AddressService/GetIMessageAvailability',
            photon_dot_imessage_dot_v1_dot_address__service__pb2.GetIMessageAvailabilityRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_address__service__pb2.GetIMessageAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
