# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/address_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'photon/imessage/v1/address_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spectrum.providers.imessage._proto.photon.imessage.v1 import address_types_pb2 as photon_dot_imessage_dot_v1_dot_address__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(photon/imessage/v1/address_service.proto\x12\x12photon.imessage.v1\x1a&photon/imessage/v1/address_types.proto\"(\n\x15GetAddressInfoRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"S\n\x16GetAddressInfoResponse\x12\x39\n\x04info\x18\x01 \x01(\x0b\x32+.photon.imessage.v1.MultiServiceAddressInfo\"(\n\x15GetFocusStatusRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"6\n\x16GetFocusStatusResponse\x12\x1c\n\x14is_silenced_by_focus\x18\x01 \x01(\x08\"1\n\x1eGetIMessageAvailabilityRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"7\n\x1fGetIMessageAvailabilityResponse\x12\x14\n\x0cis_available\x18\x01 \x01(\x08\x32\xed\x02\n\x0e\x41\x64\x64ressService\x12i\n\x0eGetAddressInfo\x12).photon.imessage.v1.GetAddressInfoRequest\x1a*.photon.imessage.v1.GetAddressInfoResponse\"\x00\x12i\n\x0eGetFocusStatus\x12).photon.imessage.v1.GetFocusStatusRequest\x1a*.photon.imessage.v1.GetFocusStatusResponse\"\x00\x12\x84\x01\n\x17GetIMessageAvailability\x12\x32.photon.imessage.v1.GetIMessageAvailabilityRequest\x1a\x33.photon.imessage.v1.GetIMessageAvailabilityResponse\"\x00\x42\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.address_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_GETADDRESSINFOREQUEST']._serialized_start=104
  _globals['_GETADDRESSINFOREQUEST']._serialized_end=144
  _globals['_GETADDRESSINFORESPONSE']._serialized_start=146
  _globals['_GETADDRESSINFORESPONSE']._serialized_end=229
  _globals['_GETFOCUSSTATUSREQUEST']._serialized_start=231
  _globals['_GETFOCUSSTATUSREQUEST']._serialized_end=271
  _globals['_GETFOCUSSTATUSRESPONSE']._serialized_start=273
  _globals['_GETFOCUSSTATUSRESPONSE']._serialized_end=327
  _globals['_GETIMESSAGEAVAILABILITYREQUEST']._serialized_start=329
  _globals['_GETIMESSAGEAVAILABILITYREQUEST']._serialized_end=378
  _globals['_GETIMESSAGEAVAILABILITYRESPONSE']._serialized_start=380
  _globals['_GETIMESSAGEAVAILABILITYRESPONSE']._serialized_end=435
  _globals['_ADDRESSSERVICE']._serialized_start=438
  _globals['_ADDRESSSERVICE']._serialized_end=803
# @@protoc_insertion_point(module_scope)
