# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/attachment_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'photon/imessage/v1/attachment_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spectrum.providers.imessage._proto.photon.imessage.v1 import attachment_types_pb2 as photon_dot_imessage_dot_v1_dot_attachment__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+photon/imessage/v1/attachment_service.proto\x12\x12photon.imessage.v1\x1a)photon/imessage/v1/attachment_types.proto\"3\n\x18GetAttachmentInfoRequest\x12\x17\n\x0f\x61ttachment_guid\x18\x01 \x01(\t\"S\n\x19GetAttachmentInfoResponse\x12\x36\n\nattachment\x18\x01 \x01(\x0b\x32\".photon.imessage.v1.AttachmentInfo\"\x7f\n\x17UploadAttachmentRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x35\n\tcompanion\x18\x03 \x01(\x0b\x32\x1d.photon.imessage.v1.CompanionH\x00\x88\x01\x01\x42\x0c\n\n_companion\"\x9b\x01\n\x18UploadAttachmentResponse\x12\x36\n\nattachment\x18\x01 \x01(\x0b\x32\".photon.imessage.v1.AttachmentInfo\x12\x39\n\tcompanion\x18\x02 \x01(\x0b\x32!.photon.imessage.v1.CompanionInfoH\x00\x88\x01\x01\x42\x0c\n\n_companion\"4\n\x19\x44ownloadAttachmentRequest\x12\x17\n\x0f\x61ttachment_guid\x18\x01 \x01(\t\"\x91\x01\n\x0e\x44ownloadHeader\x12\x36\n\nattachment\x18\x01 \x01(\x0b\x32\".photon.imessage.v1.AttachmentInfo\x12\x39\n\tcompanion\x18\x02 \x01(\x0b\x32!.photon.imessage.v1.CompanionInfoH\x00\x88\x01\x01\x42\x0c\n\n_companion\"\x91\x01\n\x1a\x44ownloadAttachmentResponse\x12\x34\n\x06header\x18\x01 \x01(\x0b\x32\".photon.imessage.v1.DownloadHeaderH\x00\x12\x17\n\rprimary_chunk\x18\x02 \x01(\x0cH\x00\x12\x19\n\x0f\x63ompanion_chunk\x18\x03 \x01(\x0cH\x00\x42\t\n\x07payload2\xed\x02\n\x11\x41ttachmentService\x12r\n\x11GetAttachmentInfo\x12,.photon.imessage.v1.GetAttachmentInfoRequest\x1a-.photon.imessage.v1.GetAttachmentInfoResponse\"\x00\x12m\n\x10UploadAttachment\x12+.photon.imessage.v1.UploadAttachmentRequest\x1a,.photon.imessage.v1.UploadAttachmentResponse\x12u\n\x12\x44ownloadAttachment\x12-.photon.imessage.v1.DownloadAttachmentRequest\x1a..photon.imessage.v1.DownloadAttachmentResponse0\x01\x42\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.attachment_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_GETATTACHMENTINFOREQUEST']._serialized_start=110
  _globals['_GETATTACHMENTINFOREQUEST']._serialized_end=161
  _globals['_GETATTACHMENTINFORESPONSE']._serialized_start=163
  _globals['_GETATTACHMENTINFORESPONSE']._serialized_end=246
  _globals['_UPLOADATTACHMENTREQUEST']._serialized_start=248
  _globals['_UPLOADATTACHMENTREQUEST']._serialized_end=375
  _globals['_UPLOADATTACHMENTRESPONSE']._serialized_start=378
  _globals['_UPLOADATTACHMENTRESPONSE']._serialized_end=533
  _globals['_DOWNLOADATTACHMENTREQUEST']._serialized_start=535
  _globals['_DOWNLOADATTACHMENTREQUEST']._serialized_end=587
  _globals['_DOWNLOADHEADER']._serialized_start=590
  _globals['_DOWNLOADHEADER']._serialized_end=735
  _globals['_DOWNLOADATTACHMENTRESPONSE']._serialized_start=738
  _globals['_DOWNLOADATTACHMENTRESPONSE']._serialized_end=883
  _globals['_ATTACHMENTSERVICE']._serialized_start=886
  _globals['_ATTACHMENTSERVICE']._serialized_end=1251
# @@protoc_insertion_point(module_scope)
