# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spectrum.providers.imessage._proto.photon.imessage.v1 import group_service_pb2 as photon_dot_imessage_dot_v1_dot_group__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in photon/imessage/v1/group_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroupServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Group-chat administration plus a durable event stream.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetDisplayName = channel.unary_unary(
                '/photon.imessage.v1.GroupService/SetDisplayName',
                request_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SetDisplayNameRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SetDisplayNameResponse.FromString,
                _registered_method=True)
        self.AddParticipants = channel.unary_unary(
                '/photon.imessage.v1.GroupService/AddParticipants',
                request_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.AddParticipantsRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.AddParticipantsResponse.FromString,
                _registered_method=True)
        self.RemoveParticipants = channel.unary_unary(
                '/photon.imessage.v1.GroupService/RemoveParticipants',
                request_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveParticipantsRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveParticipantsResponse.FromString,
                _registered_method=True)
        self.LeaveGroup = channel.unary_unary(
                '/photon.imessage.v1.GroupService/LeaveGroup',
                request_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.LeaveGroupRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetIcon = channel.unary_unary(
                '/photon.imessage.v1.GroupService/SetIcon',
                request_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SetIconRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveIcon = channel.unary_unary(
                '/photon.imessage.v1.GroupService/RemoveIcon',
                request_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveIconRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetIcon = channel.unary_unary(
                '/photon.imessage.v1.GroupService/GetIcon',
                request_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.GetIconRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.GetIconResponse.FromString,
                _registered_method=True)
        self.SubscribeGroupEvents = channel.unary_stream(
                '/photon.imessage.v1.GroupService/SubscribeGroupEvents',
                request_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SubscribeGroupEventsRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SubscribeGroupEventsResponse.FromString,
                _registered_method=True)


class GroupServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Group-chat administration plus a durable event stream.
    """

    def SetDisplayName(self, request, context):
        """Writes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddParticipants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveParticipants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGroup(self, request, context):
        """Local user voluntarily leaves the group. The chat ceases to be
        visible from this device, hence no Chat snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIcon(self, request, context):
        """Over HTTP, `data` rides base64-encoded in the JSON body (proto3-JSON
        `bytes` representation).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveIcon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIcon(self, request, context):
        """Reads. Over HTTP the icon bytes come back base64-encoded in JSON —
        acceptable at group-icon sizes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeGroupEvents(self, request, context):
        """Streams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetDisplayName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDisplayName,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SetDisplayNameRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SetDisplayNameResponse.SerializeToString,
            ),
            'AddParticipants': grpc.unary_unary_rpc_method_handler(
                    servicer.AddParticipants,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.AddParticipantsRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.AddParticipantsResponse.SerializeToString,
            ),
            'RemoveParticipants': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveParticipants,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveParticipantsRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveParticipantsResponse.SerializeToString,
            ),
            'LeaveGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGroup,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.LeaveGroupRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetIcon': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIcon,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SetIconRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveIcon': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveIcon,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveIconRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetIcon': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIcon,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.GetIconRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.GetIconResponse.SerializeToString,
            ),
            'SubscribeGroupEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeGroupEvents,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SubscribeGroupEventsRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_group__service__pb2.SubscribeGroupEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photon.imessage.v1.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photon.imessage.v1.GroupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Group-chat administration plus a durable event stream.
    """

    @staticmethod
    def SetDisplayName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.GroupService/SetDisplayName',
            photon_dot_imessage_dot_v1_dot_group__service__pb2.SetDisplayNameRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_group__service__pb2.SetDisplayNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddParticipants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.GroupService/AddParticipants',
            photon_dot_imessage_dot_v1_dot_group__service__pb2.AddParticipantsRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_group__service__pb2.AddParticipantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveParticipants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.GroupService/RemoveParticipants',
            photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveParticipantsRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveParticipantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.GroupService/LeaveGroup',
            photon_dot_imessage_dot_v1_dot_group__service__pb2.LeaveGroupRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetIcon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.GroupService/SetIcon',
            photon_dot_imessage_dot_v1_dot_group__service__pb2.SetIconRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveIcon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.GroupService/RemoveIcon',
            photon_dot_imessage_dot_v1_dot_group__service__pb2.RemoveIconRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIcon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.GroupService/GetIcon',
            photon_dot_imessage_dot_v1_dot_group__service__pb2.GetIconRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_group__service__pb2.GetIconResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeGroupEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/photon.imessage.v1.GroupService/SubscribeGroupEvents',
            photon_dot_imessage_dot_v1_dot_group__service__pb2.SubscribeGroupEventsRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_group__service__pb2.SubscribeGroupEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
