# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spectrum.providers.imessage._proto.photon.imessage.v1 import location_service_pb2 as photon_dot_imessage_dot_v1_dot_location__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in photon/imessage/v1/location_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocationServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Find My friend-location queries and live updates.
    Reads issue one-shot source queries; the watch stream forwards pushed
    observations and is not server-polled on a timer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSharedFriendLocations = channel.unary_unary(
                '/photon.imessage.v1.LocationService/ListSharedFriendLocations',
                request_serializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.ListSharedFriendLocationsRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.ListSharedFriendLocationsResponse.FromString,
                _registered_method=True)
        self.GetSharedFriendLocation = channel.unary_unary(
                '/photon.imessage.v1.LocationService/GetSharedFriendLocation',
                request_serializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.GetSharedFriendLocationRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.GetSharedFriendLocationResponse.FromString,
                _registered_method=True)
        self.RequestFriendLocationSharing = channel.unary_unary(
                '/photon.imessage.v1.LocationService/RequestFriendLocationSharing',
                request_serializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.RequestFriendLocationSharingRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.RequestFriendLocationSharingResponse.FromString,
                _registered_method=True)
        self.WatchSharedFriendLocations = channel.unary_stream(
                '/photon.imessage.v1.LocationService/WatchSharedFriendLocations',
                request_serializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.WatchSharedFriendLocationsRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.WatchSharedFriendLocationsResponse.FromString,
                _registered_method=True)


class LocationServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Find My friend-location queries and live updates.
    Reads issue one-shot source queries; the watch stream forwards pushed
    observations and is not server-polled on a timer.
    """

    def ListSharedFriendLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSharedFriendLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestFriendLocationSharing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSharedFriendLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSharedFriendLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSharedFriendLocations,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.ListSharedFriendLocationsRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.ListSharedFriendLocationsResponse.SerializeToString,
            ),
            'GetSharedFriendLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSharedFriendLocation,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.GetSharedFriendLocationRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.GetSharedFriendLocationResponse.SerializeToString,
            ),
            'RequestFriendLocationSharing': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFriendLocationSharing,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.RequestFriendLocationSharingRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.RequestFriendLocationSharingResponse.SerializeToString,
            ),
            'WatchSharedFriendLocations': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSharedFriendLocations,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.WatchSharedFriendLocationsRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_location__service__pb2.WatchSharedFriendLocationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photon.imessage.v1.LocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photon.imessage.v1.LocationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocationService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Find My friend-location queries and live updates.
    Reads issue one-shot source queries; the watch stream forwards pushed
    observations and is not server-polled on a timer.
    """

    @staticmethod
    def ListSharedFriendLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.LocationService/ListSharedFriendLocations',
            photon_dot_imessage_dot_v1_dot_location__service__pb2.ListSharedFriendLocationsRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_location__service__pb2.ListSharedFriendLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSharedFriendLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.LocationService/GetSharedFriendLocation',
            photon_dot_imessage_dot_v1_dot_location__service__pb2.GetSharedFriendLocationRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_location__service__pb2.GetSharedFriendLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestFriendLocationSharing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.LocationService/RequestFriendLocationSharing',
            photon_dot_imessage_dot_v1_dot_location__service__pb2.RequestFriendLocationSharingRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_location__service__pb2.RequestFriendLocationSharingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSharedFriendLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/photon.imessage.v1.LocationService/WatchSharedFriendLocations',
            photon_dot_imessage_dot_v1_dot_location__service__pb2.WatchSharedFriendLocationsRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_location__service__pb2.WatchSharedFriendLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
