# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/location_types.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'photon/imessage/v1/location_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'photon/imessage/v1/location_types.proto\x12\x12photon.imessage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x04\n\x14SharedFriendLocation\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08latitude\x18\x03 \x01(\x01H\x01\x88\x01\x01\x12\x16\n\tlongitude\x18\x04 \x01(\x01H\x02\x88\x01\x01\x12\x15\n\x08\x61\x63\x63uracy\x18\x05 \x01(\x01H\x03\x88\x01\x01\x12\x19\n\x0clong_address\x18\x06 \x01(\tH\x04\x88\x01\x01\x12\x1a\n\rshort_address\x18\x07 \x01(\tH\x05\x88\x01\x01\x12\x1f\n\x17is_locating_in_progress\x18\x08 \x01(\x08\x12=\n\rlocation_type\x18\t \x01(\x0e\x32&.photon.imessage.v1.FriendLocationType\x12;\n\x12location_timestamp\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x06\x88\x01\x01\x12\x33\n\nexpires_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x07\x88\x01\x01\x42\x07\n\x05_nameB\x0b\n\t_latitudeB\x0c\n\n_longitudeB\x0b\n\t_accuracyB\x0f\n\r_long_addressB\x10\n\x0e_short_addressB\x15\n\x13_location_timestampB\r\n\x0b_expires_at\"r\n\x1bSharedFriendLocationUpdated\x12\x17\n\x0fsource_sequence\x18\x01 \x01(\x04\x12:\n\x08location\x18\x02 \x01(\x0b\x32(.photon.imessage.v1.SharedFriendLocation*\x9c\x01\n\x12\x46riendLocationType\x12$\n FRIEND_LOCATION_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x46RIEND_LOCATION_TYPE_LEGACY\x10\x01\x12\x1d\n\x19\x46RIEND_LOCATION_TYPE_LIVE\x10\x02\x12 \n\x1c\x46RIEND_LOCATION_TYPE_SHALLOW\x10\x03\x42\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.location_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_FRIENDLOCATIONTYPE']._serialized_start=731
  _globals['_FRIENDLOCATIONTYPE']._serialized_end=887
  _globals['_SHAREDFRIENDLOCATION']._serialized_start=97
  _globals['_SHAREDFRIENDLOCATION']._serialized_end=612
  _globals['_SHAREDFRIENDLOCATIONUPDATED']._serialized_start=614
  _globals['_SHAREDFRIENDLOCATIONUPDATED']._serialized_end=728
# @@protoc_insertion_point(module_scope)
