# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spectrum.providers.imessage._proto.photon.imessage.v1 import poll_service_pb2 as photon_dot_imessage_dot_v1_dot_poll__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in photon/imessage/v1/poll_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PollServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Apple Polls (iOS 18+) authoring and observation.

    Every write returns the resulting `PollInfo` snapshot.

    Durable poll changes flow through `SubscribePollEvents`. For gap-free
    reconnect, pair it with `EventService.CatchUpEvents`.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePoll = channel.unary_unary(
                '/photon.imessage.v1.PollService/CreatePoll',
                request_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.CreatePollRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
                _registered_method=True)
        self.VotePoll = channel.unary_unary(
                '/photon.imessage.v1.PollService/VotePoll',
                request_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.VotePollRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
                _registered_method=True)
        self.UnvotePoll = channel.unary_unary(
                '/photon.imessage.v1.PollService/UnvotePoll',
                request_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.UnvotePollRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
                _registered_method=True)
        self.AddPollOption = channel.unary_unary(
                '/photon.imessage.v1.PollService/AddPollOption',
                request_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.AddPollOptionRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
                _registered_method=True)
        self.GetPoll = channel.unary_unary(
                '/photon.imessage.v1.PollService/GetPoll',
                request_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.GetPollRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
                _registered_method=True)
        self.SubscribePollEvents = channel.unary_stream(
                '/photon.imessage.v1.PollService/SubscribePollEvents',
                request_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.SubscribePollEventsRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.SubscribePollEventsResponse.FromString,
                _registered_method=True)


class PollServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Apple Polls (iOS 18+) authoring and observation.

    Every write returns the resulting `PollInfo` snapshot.

    Durable poll changes flow through `SubscribePollEvents`. For gap-free
    reconnect, pair it with `EventService.CatchUpEvents`.
    """

    def CreatePoll(self, request, context):
        """Writes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VotePoll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnvotePoll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPollOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoll(self, request, context):
        """Reads (poll message GUIDs are path-safe)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePollEvents(self, request, context):
        """Streams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PollServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePoll': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePoll,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.CreatePollRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.SerializeToString,
            ),
            'VotePoll': grpc.unary_unary_rpc_method_handler(
                    servicer.VotePoll,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.VotePollRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.SerializeToString,
            ),
            'UnvotePoll': grpc.unary_unary_rpc_method_handler(
                    servicer.UnvotePoll,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.UnvotePollRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.SerializeToString,
            ),
            'AddPollOption': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPollOption,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.AddPollOptionRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.SerializeToString,
            ),
            'GetPoll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoll,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.GetPollRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.SerializeToString,
            ),
            'SubscribePollEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePollEvents,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.SubscribePollEventsRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_poll__service__pb2.SubscribePollEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photon.imessage.v1.PollService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photon.imessage.v1.PollService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PollService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Apple Polls (iOS 18+) authoring and observation.

    Every write returns the resulting `PollInfo` snapshot.

    Durable poll changes flow through `SubscribePollEvents`. For gap-free
    reconnect, pair it with `EventService.CatchUpEvents`.
    """

    @staticmethod
    def CreatePoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.PollService/CreatePoll',
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.CreatePollRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VotePoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.PollService/VotePoll',
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.VotePollRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnvotePoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.PollService/UnvotePoll',
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.UnvotePollRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPollOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.PollService/AddPollOption',
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.AddPollOptionRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.PollService/GetPoll',
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.GetPollRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePollEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/photon.imessage.v1.PollService/SubscribePollEvents',
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.SubscribePollEventsRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_poll__service__pb2.SubscribePollEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
